---
title: "Atividade1 - Checkpoint3"
author: "Dandara Sousa"
date: "23 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Formule 6 perguntas que na sua opinião são relevantes, não são óbvias e que você gostaria de ver respondidas a partir dos dados. Para cada uma escreva uma frase curta que documenta qual você acha que será a resposta (adivinhando mesmo, sem fazer análise). 


1. A quantidade de episódios influencia na regularidade da temporada de uma série? 
Sim, uma série com menos episodios por temporada possua mediana mais alta que as de tempoaradas mais longas.

2. A season finale (último episodio de cada temporada) é, em geral, mais bem avaliada do que os outros episódios de uma mesma temporada?
Sim, por ser o episódio mais aguardado em uma temporada e geralmente os que a produção mais investe num geral.

3. O número de pessoas que votam nos primeiros episódios de uma temporada é maior do que os que votam no final?
Sim, porque os que avaliam negativamente no começo muito provavelmente devem deixar de assistir a série no decorrer do tempo.

4. Quanto mais antiga uma série é mais bem avaliada ela é?
Não, a qualidade da série não é afetada diretamente pelo o tempo. 

5. Uma série com mais temporadas recebe mais votos do que uma série menor?
Não, não há uma correlação entre o número de temporadas e a quantidade de votos recebidas.

6. Em geral, as notas de uma série crescem de acordo com as temporadas?
Não, avaliações negativas ocorrem a qualquer momento sem um padrão específico.

