---
title: "Atividade 1 -  Checkpoint 2"
author: "Dandara Sousa"
date: "24 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
A análise escolhida pode ser encontrada aqui: https://www.kaggle.com/viveksrinivasan/analyzing-titanic-dataset
No geral, é uma análise sobre o Titanic que aborda os perfis do passageiros a partir do gênero, da idade, do título social, do embarque, do tipo ticket e de se o passageiro sobreviveu ou não. Os gráficos utilizados foram de entendimento simples, uma pessoa que não conhece os detalhes da análise pode compreender a mensagem. Foram utilizados gráficos de barra para relação entre a sobrevivência dos passageiros e outras variáveis como o gênero, o embarque, a idade e o ticket. Para mostrar a relação entre a sobrevivência, a idade e o ticket foi utilizado um gráfico de pontos onde a cor do ponto identifica a sobrevivência/morte, o eixo x a idade e o eixo y o ticket.
A escolha dessa análise foi motivada pelo fato de ser sobre um assunto muito conhecido, trazer informações interessantes e pouco vistas como o embarque e a sobreviência, por mostrar o código de forma bem organizada (concentrando os códigos maiores após cada sessão de análise) e, também, por expor o processo de limpeza dos dados já que isso influencia na análise como um todo.
Apesar dos gráficos estarem intuitivos não há textos que norteiam o porquê de cada gráfico e o que dele pode ser extraído. Como mudança, acrescentaria uma sessão contextualizando melhor a análise e, após cada gráfico, explicaria a significância dele.

